const ADD_PRODUCT = 'ADD_PRODUCT'
const EDIT_PRODUCT = 'EDIT_MOVIE'
const DELETE_PRODUCT = 'DELETE_PRODUCT'
const GET_PRODUCT = 'GET_PRODUCT'

export {ADD_PRODUCT, EDIT_PRODUCT, DELETE_PRODUCT, GET_PRODUCT}